language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
notifications:
  slack:
    secure: jwHusOiy2esUFjYdtQddBEOs67YYrEgWHc9h0nS9lZZJobiYuNc4NzeC1WFwphswAZPT1XJnjjWG1X6o5jTLc17DNiu36i3ZIUFmTW2wJNuY7bp0RDcKSM18iJ8R5Cyk1DresZ9dIAoPWYgpj9hkaKglvPNI1Rk77yR4enX6Fl6V0fYtnCdN6RcvT+B9BS4oQcPcC7cO+ToB6p31/5M5+CUOX/RRY43235X6EVhmuIZgg7jXxCjqR9Dr0NobMIt1MRXeHqEv+SXb2FxGY/SsY5SZ3/ItTuACuFX45W5XANn7ccqHkbklKSFWi2IFuO0aOLaTd6Opcn6OgBSCYsqDV51fcjNwnH1uNJDMg6bi8/Qi1CywNT0jUNb9EDR+8PqNjwuEP3oi5GL4FOWnJecC9aeX6gCFIqFKMKScqi/84mNbvIkNnWaA+8AWeUGEsz7teRhHGVNRjQbyzPjnn0acgfYkt7hEliVRVeEu2+EzPXgmnouUo0G+yp4FkrrPLNfSga4CHqMQ5KpyssZABwtwdlh4pODAo2eHyFJrkiTYMXWu1TMlEwZf1N/cAWhC39JH0GS/onZLR89yzG00kz4LahGwun3TS5qVsvXWjQm8ighAWsAsWGemYWZmDrEy9YILZQuirN+IcyemNWzwwVX4TBc3FPpVRgLcb8VGeJOUD/g=
